plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'ch.zli.mm233'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaExec).configureEach {
    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

springBoot {
    mainClass = 'ch.zli.mm233.SecretHitlerApplication'
}

tasks.register('runConsole', JavaExec) {
    group = 'application'
    description = 'Run the basic console game.'
    mainClass = 'ch.zli.mm233.console.ConsoleApp'
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}
